### ISSUE TITLE
onPreHandler vs onRequest

### ISSUE THREAD

**Issue by antonsamper** [fs-opensource/hapi-geo-locate#1]
hi @marcuspoehls, i have been testing this plugin with some of my projects and im running into a small issue whereby the location object is undefined in some cases. I have narrowed the problem down to the server extension. Currently `request.location` is being set `onPreHandler` and this seems to work for most cases, however, i'm wondering if it would be better to set the object on `onRequest`?

In my case, I have some route validation, and if the validation fails, then the `onPreHandler` isn't triggered which means the location is never set on the `request` object and can therefore not be used later on in the `onPreResponse` extension (which is where i send my errors from to sentry.io)

What do you think?

**Comment by marcuspoehls** [comment]
Hi @antonsamper, thank you for using and testing the plugin with your use cases. And thank you very much for providing the detailed feedback about the issues you’re running into with validations!

Good point! Having the location available before applying validations will help to use it for error handling, in case the validation fails.

`hapi-geo-locate` supports [route based options](https://github.com/fs-opensource/hapi-geo-locate#plugin-route-handler-options) to enable or disable the plugin on a route basis. When using the `onRequest` extension point, hapi hasn’t determined the route to call yet which means the settings defined on a route are ignored.

**Solution idea:** the `onPreAuth` extension point within the [request lifecycle](https://hapijs.com/api#request-lifecycle) which is the next one after `onRequest` and the route to call is determined. Also, `onPreAuth` is before the validation process and the location is in place if validation fails.

What do you think?

**Comment by marcuspoehls** [comment]
@antonsamper A bug fix release `1.1.1` just went live on NPM with my proposed solution from the previous comment.

**Comment by antonsamper** [comment]
`onPreAuth` fixes the route validation issue but I would still consider putting it `onRequest` in case you want to track routes that don't exists because they are invalid or have been misspelled. 

With the `onRequest` extension:
> if no route is found or if the path violates the HTTP specification, skips to the 'onPreResponse' extension point.

**Comment by marcuspoehls** [comment]
At this point, I don’t think `onRequest` is the correct extension point, because that doesn’t allow route based plugin options. At least I don’t see how to implement them. Do I miss something here?

When using `onRequest`, the geo location functionality will (not) be executed on every request, even though you explicitly (de)activated it for a given route. 

E.g. you register `hapi-geo-locate` and disable it by default. Now you only want to activate it on the `/login` and `/signup` routes. That would not be possible when using the `onRequest` extension point, because the route isn’t determined at the time the plugin gets called (at `onRequest`) and the plugin configuration defined with registeration won’t get updated correctly.

@antonsamper In your use case, you always determine the location. Is that correct?

**Comment by antonsamper** [comment]
Ah ok, I see what the plugin is trying to achieve. I think you're right, I'm not sure if there a way to allow route based plugin options on `onRequest` as the route hasn't been defined at that point.

In my case, I always determine the location but its not a problem as I can create a catchall route and that will fix my problem.

**Comment by marcuspoehls** [comment]
I’ll do further research to verify that route based plugin configurations are not possible in `onRequest`. I’ll leave this issue open until then and share the findings with you :)

For now, the current published version `1.1.1` fixes your validation problems and your workaround with the catch-all route would allow you to still use this plugin. Have a great sunday!

**Comment by marcuspoehls** [comment]
@antonsamper I can’t find a good solution for plugin related options in `onRequest`. Sorry, can’t help you with your issue at the moment. Hope you find a solution for your use case!

**Comment by antonsamper** [comment]
No problem @marcuspoehls - thanks for having a look 😃

**Comment by marcuspoehls** [comment]
:handshake: 😊
