### ISSUE TITLE
Hapi v17 support

### ISSUE THREAD

**Issue by BorntraegerMarc** [fs-opensource/hapi-geo-locate#3]
Will this plugin be supported in hapi v17? It's listed as an official plugin in the hapi website.

**Comment by marcuspoehls** [comment]
Hi Marc, 

sure :)

We've already published an `3.0.0-rc.1` release to NPM. It supports hapi v17. As soon as hapi v17 final is released, we'll publish a final `3.0` of hapi-geo-locate.

If you already want to use hapi-geo-locate with hapi v17, please install it like this:

```
npm install hapi-geo-locate@3.0.0-rc.1
```

Does this help you?

**Comment by BorntraegerMarc** [comment]
Thanks for the answer @marcuspoehls  hapi v17 final already has been released :)

**Comment by marcuspoehls** [comment]
You're right. On GitHub the hapi v17 release is already tagged. On NPM it's still v16.

I'll tag the `3.0` release for `hapi-geo-locate` in about three hours. Thanks!

**Comment by marcuspoehls** [comment]
@BorntraegerMarc Hey Marc, `3.0.0` is tagged and available via NPM
